(()=>{var qa="undefined"!=typeof document?document.currentScript:void 0,ia=ra=>new Promise((Pa,R)=>{function sa(a,b,c,e){a||(a=this);this.parent=a;this.Y=a.Y;this.Pa=null;this.id=d.Ac++;this.name=b;this.mode=c;this.S={};this.T={};this.Ra=e}function ba(){Q--;if(0==Q&&(null!==ja&&(clearInterval(ja),ja=null),V)){var a=V;V=null;a()}}function I(a){if(r.onAbort)r.onAbort(a);a="Aborted("+a+")";J(a);ta=!0;ca=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function ua(a){return a.startsWith("data:application/octet-stream;base64,")}
function va(a){if(a==W&&da)return new Uint8Array(da);if(wa)return wa(a);throw"both async and sync fetching of the wasm failed";}function Qa(a){return da||"function"!=typeof fetch?Promise.resolve().then(()=>va(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>va(a))}function xa(a,b,c){return Qa(a).then(e=>WebAssembly.instantiate(e,b)).then(e=>e).then(c,e=>{J(`failed to asynchronously prepare wasm: ${e}`);
I(e)})}function Ra(a,b,c,e){return a||"function"!=typeof WebAssembly.instantiateStreaming||ua(b)||"function"!=typeof fetch?xa(b,c,e):fetch(b,{credentials:"same-origin"}).then(f=>WebAssembly.instantiateStreaming(f,c).then(e,function(g){J(`wasm streaming compile failed: ${g}`);J("falling back to ArrayBuffer instantiation");return xa(b,c,e)}))}function ya(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}function ka(a,b,c){c=0<c?c:X(a)+1;c=Array(c);a=S(a,c,0,c.length);
b&&(c.length=a);return c}function za(a=[]){var b=Aa;a.unshift(Ba);var c=a.length,e=la(4*(c+1)),f=e;a.forEach(k=>{var n=A,q=f>>2,p=X(k)+1,u=la(p);S(k,G,u,p);n[q]=u;f+=4});A[f>>2]=0;try{var g=b(c,e);Ca(g,!0);return g}catch(k){if(k instanceof ya||"unwind"==k)a=ca;else throw k;return a}}function Da(a=Ea){if(!(0<Q||(ea(Sa),0<Q||fa||(fa=!0,r.calledRun=!0,ta)))){r.noFSInit||d.ta.kb||d.ta();d.Ib=!1;K.ta();ea(Fa);ea(Ta);if(r.onRuntimeInitialized)r.onRuntimeInitialized();Ua&&za(a);ea(Va)}}var r;r||(r=typeof Module !== 'undefined' ? Module : {});
var ha;r.printErr=a=>ha+=`${a}\n`;r.onAbort=R;r.onRuntimeInitialized=()=>Pa((a,b)=>{ha="";b=b?`size ${b.x},${b.y}`:"";d.Qc("input",a?a:"");za(["-e",`set o "output";set t svg ${b} dynamic enhanced;`,"input"]);a=d.Gc("output",{encoding:"utf8"});d.qa("input");d.qa("output");if(ha)throw Error(ha);return a});r.instantiateWasm="function"===typeof ra?ra:void 0;R=Object.assign({},r);var Ea=[],Ba="./this.program",T="",wa;"undefined"!=typeof document&&qa&&(T=qa.src);T=0!==T.indexOf("blob:")?T.substr(0,T.replace(/[?#].*/,
"").lastIndexOf("/")+1):"";var Ga=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};var Wa=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var Ha=console.log.bind(console),J=r.printErr||console.error.bind(console);Object.assign(r,R);R=null;r.arguments&&(Ea=r.arguments);var da;"object"!=typeof WebAssembly&&I("no native wasm support detected");
var Ia,ta=!1,ca,E,G,U,m,A,Sa=[],Fa=[],Ta=[],Va=[],Q=0,ja=null,V=null;var W="gnuplot.wasm";ua(W)||(W=T+W);var l,w,ea=a=>{for(;0<a.length;)a.shift()(r)},x={mb:a=>"/"===a.charAt(0),Jc:a=>/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1),Mb:(a,b)=>{for(var c=0,e=a.length-1;0<=e;e--){var f=a[e];"."===f?a.splice(e,1):".."===f?(a.splice(e,1),c++):c&&(a.splice(e,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},normalize:a=>{var b=x.mb(a),c="/"===a.substr(-1);(a=x.Mb(a.split("/").filter(e=>
!!e),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},dirname:a=>{var b=x.Jc(a);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},ra:a=>{if("/"===a)return"/";a=x.normalize(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},join:function(){return x.normalize(Array.prototype.slice.call(arguments).join("/"))},wa:(a,b)=>x.normalize(a+"/"+b)},Xa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);
I("initRandomDevice")},Ja=a=>(Ja=Xa())(a),H={resolve:function(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:d.Wa();if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b=x.mb(b)}a=x.Mb(a.split("/").filter(e=>!!e),!b).join("/");return(b?"/":"")+a||"."},Nb:(a,b)=>{function c(k){for(var n=0;n<k.length&&""===k[n];n++);for(var q=k.length-1;0<=q&&""===k[q];q--);return n>q?[]:k.slice(n,q-n+1)}a=H.resolve(a).substr(1);
b=H.resolve(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var e=Math.min(a.length,b.length),f=e,g=0;g<e;g++)if(a[g]!==b[g]){f=g;break}e=[];for(g=f;g<a.length;g++)e.push("..");e=e.concat(b.slice(f));return e.join("/")}},Ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,L=(a,b,c)=>{var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|
g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},ma=[],X=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},S=(a,b,c,e)=>{if(!(0<e))return 0;var f=c;e=c+e-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);
k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=e)break;b[c++]=k}else{if(2047>=k){if(c+1>=e)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=e)break;b[c++]=224|k>>12}else{if(c+3>=e)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-f},K={Qb:[],ta(){},rd(){},register(a,b){K.Qb[a]={input:[],ba:[],ma:b};d.sb(a,K.T)},T:{open(a){var b=K.Qb[a.node.Ra];if(!b)throw new d.R(43);a.V=b;a.seekable=!1},close(a){a.V.ma.Xa(a.V)},Xa(a){a.V.ma.Xa(a.V)},read(a,b,c,e){if(!a.V||
!a.V.ma.Fb)throw new d.R(60);for(var f=0,g=0;g<e;g++){try{var k=a.V.ma.Fb(a.V)}catch(n){throw new d.R(29);}if(void 0===k&&0===f)throw new d.R(6);if(null===k||void 0===k)break;f++;b[c+g]=k}f&&(a.node.timestamp=Date.now());return f},write(a,b,c,e){if(!a.V||!a.V.ma.pb)throw new d.R(60);try{for(var f=0;f<e;f++)a.V.ma.pb(a.V,b[c+f])}catch(g){throw new d.R(29);}e&&(a.node.timestamp=Date.now());return f}},jc:{Fb(){a:{if(!ma.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?
(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}ma=ka(a,!0)}a=ma.shift()}return a},pb(a,b){null===b||10===b?(Ha(L(a.ba,0)),a.ba=[]):0!=b&&a.ba.push(b)},Xa(a){a.ba&&0<a.ba.length&&(Ha(L(a.ba,0)),a.ba=[])},rc(){return{Vc:25856,Xc:5,Uc:191,Wc:35387,Tc:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},sc(){return 0},tc(){return[24,80]}},ic:{pb(a,b){null===b||10===b?(J(L(a.ba,0)),a.ba=[]):
0!=b&&a.ba.push(b)},Xa(a){a.ba&&0<a.ba.length&&(J(L(a.ba,0)),a.ba=[])}}},t={ia:null,Y(){return t.createNode(null,"/",16895,0)},createNode(a,b,c,e){if(d.uc(c)||d.vc(c))throw new d.R(63);t.ia||(t.ia={dir:{node:{fa:t.S.fa,aa:t.S.aa,xa:t.S.xa,la:t.S.la,Sa:t.S.Sa,qa:t.S.qa,Ia:t.S.Ia,Ha:t.S.Ha,pa:t.S.pa},stream:{ca:t.T.ca}},file:{node:{fa:t.S.fa,aa:t.S.aa},stream:{ca:t.T.ca,read:t.T.read,write:t.T.write,Ka:t.T.Ka,Fa:t.T.Fa,Ga:t.T.Ga}},link:{node:{fa:t.S.fa,aa:t.S.aa,Ba:t.S.Ba},stream:{}},wb:{node:{fa:t.S.fa,
aa:t.S.aa},stream:d.Zb}});c=d.createNode(a,b,c,e);d.Z(c.mode)?(c.S=t.ia.dir.node,c.T=t.ia.dir.stream,c.U={}):d.isFile(c.mode)?(c.S=t.ia.file.node,c.T=t.ia.file.stream,c.X=0,c.U=null):d.ua(c.mode)?(c.S=t.ia.link.node,c.T=t.ia.link.stream):d.Na(c.mode)&&(c.S=t.ia.wb.node,c.T=t.ia.wb.stream);c.timestamp=Date.now();a&&(a.U[b]=c,a.timestamp=c.timestamp);return c},fd(a){return a.U?a.U.subarray?a.U.subarray(0,a.X):new Uint8Array(a.U):new Uint8Array(0)},Cb(a,b){var c=a.U?a.U.length:0;c>=b||(b=Math.max(b,
c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.U,a.U=new Uint8Array(b),0<a.X&&a.U.set(c.subarray(0,a.X),0))},Hc(a,b){if(a.X!=b)if(0==b)a.U=null,a.X=0;else{var c=a.U;a.U=new Uint8Array(b);c&&a.U.set(c.subarray(0,Math.min(b,a.X)));a.X=b}},S:{fa(a){var b={};b.kc=d.Na(a.mode)?a.id:1;b.Jb=a.id;b.mode=a.mode;b.Cc=1;b.uid=0;b.qc=0;b.Ra=a.Ra;d.Z(a.mode)?b.size=4096:d.isFile(a.mode)?b.size=a.X:d.ua(a.mode)?b.size=a.link.length:b.size=0;b.Ub=new Date(a.timestamp);b.zc=new Date(a.timestamp);b.hc=new Date(a.timestamp);
b.Vb=4096;b.Wb=Math.ceil(b.size/b.Vb);return b},aa(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&t.Hc(a,b.size)},xa(){throw d.ib[44];},la(a,b,c,e){return t.createNode(a,b,c,e)},Sa(a,b,c){if(d.Z(a.mode)){try{var e=d.ga(b,c)}catch(g){}if(e)for(var f in e.U)throw new d.R(55);}delete a.parent.U[a.name];a.parent.timestamp=Date.now();a.name=c;b.U[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},qa(a,b){delete a.U[b];a.timestamp=Date.now()},Ia(a,b){var c=
d.ga(a,b),e;for(e in c.U)throw new d.R(55);delete a.U[b];a.timestamp=Date.now()},Ha(a){var b=[".",".."],c;for(c in a.U)a.U.hasOwnProperty(c)&&b.push(c);return b},pa(a,b,c){a=t.createNode(a,b,41471,0);a.link=c;return a},Ba(a){if(!d.ua(a.mode))throw new d.R(28);return a.link}},T:{read(a,b,c,e,f){var g=a.node.U;if(f>=a.node.X)return 0;a=Math.min(a.node.X-f,e);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(e=0;e<a;e++)b[c+e]=g[f+e];return a},write(a,b,c,e,f,g){if(!e)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.U||a.U.subarray)){if(g)return a.U=b.subarray(c,c+e),a.X=e;if(0===a.X&&0===f)return a.U=b.slice(c,c+e),a.X=e;if(f+e<=a.X)return a.U.set(b.subarray(c,c+e),f),e}t.Cb(a,f+e);if(a.U.subarray&&b.subarray)a.U.set(b.subarray(c,c+e),f);else for(g=0;g<e;g++)a.U[f+g]=b[c+g];a.X=Math.max(a.X,f+e);return e},ca(a,b,c){1===c?b+=a.position:2===c&&d.isFile(a.node.mode)&&(b+=a.node.X);if(0>b)throw new d.R(28);return b},Ka(a,b,c){t.Cb(a.node,b+c);a.node.X=Math.max(a.node.X,b+c)},Fa(a,b,
c,e,f){if(!d.isFile(a.node.mode))throw new d.R(43);a=a.node.U;if(f&2||a.buffer!==E.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;I();b=void 0;if(!b)throw new d.R(48);E.set(a,b)}else c=!1,b=a.byteOffset;return{pd:b,Sc:c}},Ga(a,b,c,e){t.T.write(a,b,0,e,c,!1);return 0}}},Ya=(a,b,c,e)=>{var f=e?"":`al ${a}`;Wa(a,g=>{g||I(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(g));f&&ba(f)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;
});f&&Q++},Za=[],$a=(a,b,c,e)=>{"undefined"!=typeof Browser&&Browser.ta();var f=!1;Za.forEach(g=>{!f&&g.canHandle(b)&&(g.handle(a,b,c,e),f=!0)});return f},na=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},d={root:null,Qa:[],zb:{},streams:[],Ac:1,ha:null,yb:"/",kb:!1,Ib:!0,R:null,ib:{},nc:null,bb:0,W(a,b={}){a=H.resolve(a);if(!a)return{path:"",node:null};b=Object.assign({gb:!0,rb:0},b);if(8<b.rb)throw new d.R(32);a=a.split("/").filter(k=>!!k);for(var c=d.root,e="/",f=0;f<a.length;f++){var g=f===
a.length-1;if(g&&b.parent)break;c=d.ga(c,a[f]);e=x.wa(e,a[f]);d.va(c)&&(!g||g&&b.gb)&&(c=c.Pa.root);if(!g||b.ea)for(g=0;d.ua(c.mode);)if(c=d.Ba(e),e=H.resolve(x.dirname(e),c),c=d.W(e,{rb:b.rb+1}).node,40<g++)throw new d.R(32);}return{path:e,node:c}},oa(a){for(var b;;){if(d.Za(a))return a=a.Y.Lb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},jb(a,b){for(var c=0,e=0;e<b.length;e++)c=(c<<5)-c+b.charCodeAt(e)|0;return(a+c>>>0)%d.ha.length},Gb(a){var b=d.jb(a.parent.id,
a.name);a.za=d.ha[b];d.ha[b]=a},Hb(a){var b=d.jb(a.parent.id,a.name);if(d.ha[b]===a)d.ha[b]=a.za;else for(b=d.ha[b];b;){if(b.za===a){b.za=a.za;break}b=b.za}},ga(a,b){var c=d.xc(a);if(c)throw new d.R(c,a);for(c=d.ha[d.jb(a.id,b)];c;c=c.za){var e=c.name;if(c.parent.id===a.id&&e===b)return c}return d.xa(a,b)},createNode(a,b,c,e){a=new d.Rb(a,b,c,e);d.Gb(a);return a},fb(a){d.Hb(a)},Za(a){return a===a.parent},va(a){return!!a.Pa},isFile(a){return 32768===(a&61440)},Z(a){return 16384===(a&61440)},ua(a){return 40960===
(a&61440)},Na(a){return 8192===(a&61440)},uc(a){return 24576===(a&61440)},vc(a){return 4096===(a&61440)},gd(a){return 49152===(a&49152)},Db(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b},Aa(a,b){if(d.Ib)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},xc(a){var b=d.Aa(a,"x");return b?b:a.S.xa?0:2},ob(a,b){try{return d.ga(a,b),20}catch(c){}return d.Aa(a,"wx")},$a(a,b,c){try{var e=d.ga(a,b)}catch(f){return f.$}if(a=
d.Aa(a,"wx"))return a;if(c){if(!d.Z(e.mode))return 54;if(d.Za(e)||d.oa(e)===d.Wa())return 10}else if(d.Z(e.mode))return 31;return 0},yc(a,b){return a?d.ua(a.mode)?32:d.Z(a.mode)&&("r"!==d.Db(b)||b&512)?31:d.Aa(a,d.Db(b)):44},Sb:4096,Bc(){for(var a=0;a<=d.Sb;a++)if(!d.streams[a])return a;throw new d.R(33);},Ma(a){a=d.pc(a);if(!a)throw new d.R(8);return a},pc:a=>d.streams[a],xb(a,b=-1){d.Ta||(d.Ta=function(){this.Ua={}},d.Ta.prototype={},Object.defineProperties(d.Ta.prototype,{object:{get(){return this.node},
set(c){this.node=c}},flags:{get(){return this.Ua.flags},set(c){this.Ua.flags=c}},position:{get(){return this.Ua.position},set(c){this.Ua.position=c}}}));a=Object.assign(new d.Ta,a);-1==b&&(b=d.Bc());a.La=b;return d.streams[b]=a},$b(a){d.streams[a]=null},Zb:{open(a){a.T=d.oc(a.node.Ra).T;a.T.open&&a.T.open(a)},ca(){throw new d.R(70);}},nb:a=>a>>8,ld:a=>a&255,ya:(a,b)=>a<<8|b,sb(a,b){d.zb[a]={T:b}},oc:a=>d.zb[a],Eb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push.apply(a,c.Qa)}return b},
Pb(a,b){function c(k){d.bb--;return b(k)}function e(k){if(k){if(!e.mc)return e.mc=!0,c(k)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);d.bb++;1<d.bb&&J(`warning: ${d.bb} FS.syncfs operations in flight at once, probably just doing extra work`);var f=d.Eb(d.root.Y),g=0;f.forEach(k=>{if(!k.type.Pb)return e(null);k.type.Pb(k,a,e)})},Y(a,b,c){var e="/"===c,f=!c;if(e&&d.root)throw new d.R(10);if(!e&&!f){var g=d.W(c,{gb:!1});c=g.path;g=g.node;if(d.va(g))throw new d.R(10);if(!d.Z(g.mode))throw new d.R(54);
}b={type:a,od:b,Lb:c,Qa:[]};a=a.Y(b);a.Y=b;b.root=a;e?d.root=a:g&&(g.Pa=b,g.Y&&g.Y.Qa.push(b));return a},td(a){a=d.W(a,{gb:!1});if(!d.va(a.node))throw new d.R(28);a=a.node;var b=a.Pa,c=d.Eb(b);Object.keys(d.ha).forEach(e=>{for(e=d.ha[e];e;){var f=e.za;c.includes(e.Y)&&d.fb(e);e=f}});a.Pa=null;a.Y.Qa.splice(a.Y.Qa.indexOf(b),1)},xa(a,b){return a.S.xa(a,b)},la(a,b,c){var e=d.W(a,{parent:!0}).node;a=x.ra(a);if(!a||"."===a||".."===a)throw new d.R(28);var f=d.ob(e,a);if(f)throw new d.R(f);if(!e.S.la)throw new d.R(63);
return e.S.la(e,a,b,c)},create(a,b){return d.la(a,(void 0!==b?b:438)&4095|32768,0)},da(a,b){return d.la(a,(void 0!==b?b:511)&1023|16384,0)},md(a,b){a=a.split("/");for(var c="",e=0;e<a.length;++e)if(a[e]){c+="/"+a[e];try{d.da(c,b)}catch(f){if(20!=f.$)throw f;}}},ab(a,b,c){"undefined"==typeof c&&(c=b,b=438);return d.la(a,b|8192,c)},pa(a,b){if(!H.resolve(a))throw new d.R(44);var c=d.W(b,{parent:!0}).node;if(!c)throw new d.R(44);b=x.ra(b);var e=d.ob(c,b);if(e)throw new d.R(e);if(!c.S.pa)throw new d.R(63);
return c.S.pa(c,b,a)},Sa(a,b){var c=x.dirname(a),e=x.dirname(b),f=x.ra(a),g=x.ra(b);var k=d.W(a,{parent:!0});var n=k.node;k=d.W(b,{parent:!0});k=k.node;if(!n||!k)throw new d.R(44);if(n.Y!==k.Y)throw new d.R(75);var q=d.ga(n,f);a=H.Nb(a,e);if("."!==a.charAt(0))throw new d.R(28);a=H.Nb(b,c);if("."!==a.charAt(0))throw new d.R(55);try{var p=d.ga(k,g)}catch(u){}if(q!==p){b=d.Z(q.mode);if(f=d.$a(n,f,b))throw new d.R(f);if(f=p?d.$a(k,g,b):d.ob(k,g))throw new d.R(f);if(!n.S.Sa)throw new d.R(63);if(d.va(q)||
p&&d.va(p))throw new d.R(10);if(k!==n&&(f=d.Aa(n,"w")))throw new d.R(f);d.Hb(q);try{n.S.Sa(q,k,g)}catch(u){throw u;}finally{d.Gb(q)}}},Ia(a){var b=d.W(a,{parent:!0}).node;a=x.ra(a);var c=d.ga(b,a),e=d.$a(b,a,!0);if(e)throw new d.R(e);if(!b.S.Ia)throw new d.R(63);if(d.va(c))throw new d.R(10);b.S.Ia(b,a);d.fb(c)},Ha(a){a=d.W(a,{ea:!0}).node;if(!a.S.Ha)throw new d.R(54);return a.S.Ha(a)},qa(a){var b=d.W(a,{parent:!0}).node;if(!b)throw new d.R(44);a=x.ra(a);var c=d.ga(b,a),e=d.$a(b,a,!1);if(e)throw new d.R(e);
if(!b.S.qa)throw new d.R(63);if(d.va(c))throw new d.R(10);b.S.qa(b,a);d.fb(c)},Ba(a){a=d.W(a).node;if(!a)throw new d.R(44);if(!a.S.Ba)throw new d.R(28);return H.resolve(d.oa(a.parent),a.S.Ba(a))},stat(a,b){a=d.W(a,{ea:!b}).node;if(!a)throw new d.R(44);if(!a.S.fa)throw new d.R(63);return a.S.fa(a)},kd(a){return d.stat(a,!0)},Va(a,b,c){a="string"==typeof a?d.W(a,{ea:!c}).node:a;if(!a.S.aa)throw new d.R(63);a.S.aa(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},hd(a,b){d.Va(a,b,!0)},bd(a,b){a=d.Ma(a);
d.Va(a.node,b)},vb(a,b,c,e){a="string"==typeof a?d.W(a,{ea:!e}).node:a;if(!a.S.aa)throw new d.R(63);a.S.aa(a,{timestamp:Date.now()})},jd(a,b,c){d.vb(a,b,c,!0)},cd(a,b,c){a=d.Ma(a);d.vb(a.node,b,c)},truncate(a,b){if(0>b)throw new d.R(28);a="string"==typeof a?d.W(a,{ea:!0}).node:a;if(!a.S.aa)throw new d.R(63);if(d.Z(a.mode))throw new d.R(31);if(!d.isFile(a.mode))throw new d.R(28);var c=d.Aa(a,"w");if(c)throw new d.R(c);a.S.aa(a,{size:b,timestamp:Date.now()})},ed(a,b){a=d.Ma(a);if(0===(a.flags&2097155))throw new d.R(28);
d.truncate(a.node,b)},ud(a,b,c){a=d.W(a,{ea:!0}).node;a.S.aa(a,{timestamp:Math.max(b,c)})},open(a,b,c){if(""===a)throw new d.R(44);if("string"==typeof b){var e={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof e)throw Error(`Unknown file open mode: ${b}`);b=e}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=x.normalize(a);try{f=d.W(a,{ea:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new d.R(20);}else f=d.la(a,c,0),e=!0;if(!f)throw new d.R(44);
d.Na(f.mode)&&(b&=-513);if(b&65536&&!d.Z(f.mode))throw new d.R(54);if(!e&&(c=d.yc(f,b)))throw new d.R(c);b&512&&!e&&d.truncate(f,0);b&=-131713;f=d.xb({node:f,path:d.oa(f),flags:b,seekable:!0,position:0,T:f.T,Pc:[],error:!1});f.T.open&&f.T.open(f);!r.logReadFiles||b&1||(d.qb||(d.qb={}),a in d.qb||(d.qb[a]=1));return f},close(a){if(d.Oa(a))throw new d.R(8);a.sa&&(a.sa=null);try{a.T.close&&a.T.close(a)}catch(b){throw b;}finally{d.$b(a.La)}a.La=null},Oa(a){return null===a.La},ca(a,b,c){if(d.Oa(a))throw new d.R(8);
if(!a.seekable||!a.T.ca)throw new d.R(70);if(0!=c&&1!=c&&2!=c)throw new d.R(28);a.position=a.T.ca(a,b,c);a.Pc=[];return a.position},read(a,b,c,e,f){if(0>e||0>f)throw new d.R(28);if(d.Oa(a))throw new d.R(8);if(1===(a.flags&2097155))throw new d.R(8);if(d.Z(a.node.mode))throw new d.R(31);if(!a.T.read)throw new d.R(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new d.R(70);b=a.T.read(a,b,c,e,f);g||(a.position+=b);return b},write(a,b,c,e,f,g){if(0>e||0>f)throw new d.R(28);
if(d.Oa(a))throw new d.R(8);if(0===(a.flags&2097155))throw new d.R(8);if(d.Z(a.node.mode))throw new d.R(31);if(!a.T.write)throw new d.R(28);a.seekable&&a.flags&1024&&d.ca(a,0,2);var k="undefined"!=typeof f;if(!k)f=a.position;else if(!a.seekable)throw new d.R(70);b=a.T.write(a,b,c,e,f,g);k||(a.position+=b);return b},Ka(a,b,c){if(d.Oa(a))throw new d.R(8);if(0>b||0>=c)throw new d.R(28);if(0===(a.flags&2097155))throw new d.R(8);if(!d.isFile(a.node.mode)&&!d.Z(a.node.mode))throw new d.R(43);if(!a.T.Ka)throw new d.R(138);
a.T.Ka(a,b,c)},Fa(a,b,c,e,f){if(0!==(e&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new d.R(2);if(1===(a.flags&2097155))throw new d.R(2);if(!a.T.Fa)throw new d.R(43);return a.T.Fa(a,b,c,e,f)},Ga(a,b,c,e,f){return a.T.Ga?a.T.Ga(a,b,c,e,f):0},nd:()=>0,lb(a,b,c){if(!a.T.lb)throw new d.R(59);return a.T.lb(a,b,c)},Gc(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,e=d.open(a,b.flags);a=d.stat(a).size;
var f=new Uint8Array(a);d.read(e,f,0,a,0);"utf8"===b.encoding?c=L(f,0):"binary"===b.encoding&&(c=f);d.close(e);return c},Qc(a,b,c={}){c.flags=c.flags||577;a=d.open(a,c.flags,c.mode);if("string"==typeof b){var e=new Uint8Array(X(b)+1);b=S(b,e,0,e.length);d.write(a,e,0,b,void 0,c.Xb)}else if(ArrayBuffer.isView(b))d.write(a,b,0,b.byteLength,void 0,c.Xb);else throw Error("Unsupported data type");d.close(a)},Wa:()=>d.yb,Yb(a){a=d.W(a,{ea:!0});if(null===a.node)throw new d.R(44);if(!d.Z(a.node.mode))throw new d.R(54);
var b=d.Aa(a.node,"x");if(b)throw new d.R(b);d.yb=a.path},cc(){d.da("/tmp");d.da("/home");d.da("/home/web_user")},bc(){d.da("/dev");d.sb(d.ya(1,3),{read:()=>0,write:(e,f,g,k)=>k});d.ab("/dev/null",d.ya(1,3));K.register(d.ya(5,0),K.jc);K.register(d.ya(6,0),K.ic);d.ab("/dev/tty",d.ya(5,0));d.ab("/dev/tty1",d.ya(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ja(a).byteLength);return a[--b]};d.na("/dev","random",c);d.na("/dev","urandom",c);d.da("/dev/shm");d.da("/dev/shm/tmp")},ec(){d.da("/proc");
var a=d.da("/proc/self");d.da("/proc/self/fd");d.Y({Y(){var b=d.createNode(a,"fd",16895,73);b.S={xa(c,e){var f=d.Ma(+e);c={parent:null,Y:{Lb:"fake"},S:{Ba:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")},fc(){r.stdin?d.na("/dev","stdin",r.stdin):d.pa("/dev/tty","/dev/stdin");r.stdout?d.na("/dev","stdout",null,r.stdout):d.pa("/dev/tty","/dev/stdout");r.stderr?d.na("/dev","stderr",null,r.stderr):d.pa("/dev/tty1","/dev/stderr");d.open("/dev/stdin",0);d.open("/dev/stdout",1);d.open("/dev/stderr",
1)},Ab(){d.R||(d.R=function(a,b){this.name="ErrnoError";this.node=b;this.Ic=function(c){this.$=c};this.Ic(a);this.message="FS error"},d.R.prototype=Error(),d.R.prototype.constructor=d.R,[44].forEach(a=>{d.ib[a]=new d.R(a);d.ib[a].stack="<generic error, no stack>"}))},Kc(){d.Ab();d.ha=Array(4096);d.Y(t,{},"/");d.cc();d.bc();d.ec();d.nc={MEMFS:t}},ta(a,b,c){d.ta.kb=!0;d.Ab();r.stdin=a||r.stdin;r.stdout=b||r.stdout;r.stderr=c||r.stderr;d.fc()},qd(){d.ta.kb=!1;for(var a=0;a<d.streams.length;a++){var b=
d.streams[a];b&&d.close(b)}},dd(a,b){a=d.Tb(a,b);return a.Bb?a.object:null},Tb(a,b){try{var c=d.W(a,{ea:!b});a=c.path}catch(f){}var e={Za:!1,Bb:!1,error:0,name:null,path:null,object:null,Dc:!1,Fc:null,Ec:null};try{c=d.W(a,{parent:!0}),e.Dc=!0,e.Fc=c.path,e.Ec=c.node,e.name=x.ra(a),c=d.W(a,{ea:!b}),e.Bb=!0,e.path=c.path,e.object=c.node,e.name=c.node.name,e.Za="/"===c.path}catch(f){e.error=f.$}return e},Zc(a,b){a="string"==typeof a?a:d.oa(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var e=
x.wa(a,c);try{d.da(e)}catch(f){}a=e}}return e},dc(a,b,c,e,f){a=x.wa("string"==typeof a?a:d.oa(a),b);e=na(e,f);return d.create(a,e)},ac(a,b,c,e,f,g){var k=b;a&&(a="string"==typeof a?a:d.oa(a),k=b?x.wa(a,b):a);a=na(e,f);k=d.create(k,a);if(c){if("string"==typeof c){b=Array(c.length);e=0;for(f=c.length;e<f;++e)b[e]=c.charCodeAt(e);c=b}d.Va(k,a|146);b=d.open(k,577);d.write(b,c,0,c.length,0,g);d.close(b);d.Va(k,a)}return k},na(a,b,c,e){a=x.wa("string"==typeof a?a:d.oa(a),b);b=na(!!c,!!e);d.na.nb||(d.na.nb=
64);var f=d.ya(d.na.nb++,0);d.sb(f,{open(g){g.seekable=!1},close(){e&&e.buffer&&e.buffer.length&&e(10)},read(g,k,n,q){for(var p=0,u=0;u<q;u++){try{var z=c()}catch(C){throw new d.R(29);}if(void 0===z&&0===p)throw new d.R(6);if(null===z||void 0===z)break;p++;k[n+u]=z}p&&(g.node.timestamp=Date.now());return p},write(g,k,n,q){for(var p=0;p<q;p++)try{e(k[n+p])}catch(u){throw new d.R(29);}q&&(g.node.timestamp=Date.now());return p}});return d.ab(a,b,f)},hb(a){if(a.Kb||a.wc||a.link||a.U)return!0;if("undefined"!=
typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(Ga)try{a.U=ka(Ga(a.url),!0),a.X=a.U.length}catch(b){throw new d.R(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");},Yc(a,b,c,e,f){if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
c={Kb:!1,url:c};var g=d.dc(a,b,c,e,f);c.U?g.U=c.U:c.url&&(g.U=null,g.url=c.url);Object.defineProperties(g,{X:{get:function(){return this.U.length}}});var k={};Object.keys(g.T).forEach(n=>{var q=g.T[n];k[n]=function(){d.hb(g);return q.apply(null,arguments)}});k.read=(n,q,p,u,z)=>{d.hb(g);n=n.node.U;if(z>=n.length)q=0;else{u=Math.min(n.length-z,u);if(n.slice)for(var C=0;C<u;C++)q[p+C]=n[z+C];else for(C=0;C<u;C++)q[p+C]=n.get(z+C);q=u}return q};k.Fa=()=>{d.hb(g);I();throw new d.R(48);};g.T=k;return g}},
v={Rc:5,ub(a,b,c){if(x.mb(b))return b;a=-100===a?d.Wa():v.ka(a).path;if(0==b.length){if(!c)throw new d.R(44);return a}return x.wa(a,b)},lc(a,b,c){try{var e=a(b)}catch(g){if(g&&g.node&&x.normalize(b)!==x.normalize(d.oa(g.node)))return-54;throw g;}m[c>>2]=e.kc;m[c+4>>2]=e.mode;A[c+8>>2]=e.Cc;m[c+12>>2]=e.uid;m[c+16>>2]=e.qc;m[c+20>>2]=e.Ra;w=[e.size>>>0,(l=e.size,1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[c+24>>2]=w[0];m[c+28>>2]=w[1];m[c+32>>
2]=4096;m[c+36>>2]=e.Wb;a=e.Ub.getTime();b=e.zc.getTime();var f=e.hc.getTime();w=[Math.floor(a/1E3)>>>0,(l=Math.floor(a/1E3),1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[c+40>>2]=w[0];m[c+44>>2]=w[1];A[c+48>>2]=a%1E3*1E3;w=[Math.floor(b/1E3)>>>0,(l=Math.floor(b/1E3),1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[c+56>>2]=w[0];m[c+60>>2]=w[1];A[c+64>>2]=b%1E3*1E3;w=[Math.floor(f/1E3)>>>0,(l=
Math.floor(f/1E3),1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[c+72>>2]=w[0];m[c+76>>2]=w[1];A[c+80>>2]=f%1E3*1E3;w=[e.Jb>>>0,(l=e.Jb,1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[c+88>>2]=w[0];m[c+92>>2]=w[1];return 0},ad(a,b,c,e,f){if(!d.isFile(b.node.mode))throw new d.R(43);if(e&2)return 0;d.Ga(b,G.slice(a,a+c),f,c,e)},Ja:void 0,get(){var a=m[+v.Ja>>2];v.Ja+=4;return a},Ea(){return v.get()},
Ya(a){return a?L(G,a,void 0):""},ka(a){return d.Ma(a)}},Y=a=>0===a%4&&(0!==a%100||0===a%400),ab=[0,31,60,91,121,152,182,213,244,274,305,335],bb=[0,31,59,90,120,151,181,212,243,273,304,334],Ma=a=>{var b=X(a)+1,c=La(b);c&&S(a,G,c,b);return c},oa={},Z=()=>{if(!Z.Ob){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:Ba||"./this.program"},b;for(b in oa)void 0===
oa[b]?delete a[b]:a[b]=oa[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Z.Ob=c}return Z.Ob},Ca=a=>{ca=ca=a;throw new ya(a);};R=Ca;var Na=[31,29,31,30,31,30,31,31,30,31,30,31],Oa=[31,28,31,30,31,30,31,31,30,31,30,31],M;Object.defineProperties(sa.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},wc:{get:function(){return d.Z(this.mode)}},
Kb:{get:function(){return d.Na(this.mode)}}});d.Rb=sa;d.$c=(a,b,c,e,f,g,k,n,q,p)=>{function u(h){function y(B){p&&p();n||d.ac(a,b,B,e,f,q);g&&g();ba(C)}$a(h,z,y,()=>{k&&k();ba(C)})||y(h)}var z=b?H.resolve(x.wa(a,b)):a,C=`cp ${z}`;Q++;"string"==typeof c?Ya(c,h=>u(h),k):u(c)};d.Kc();var cb={p:function(a){try{return a=v.Ya(a),d.Yb(a),0}catch(b){if("undefined"==typeof d||"ErrnoError"!==b.name)throw b;return-b.$}},m:function(a,b,c){v.Ja=c;try{var e=v.ka(a);switch(b){case 0:var f=v.get();if(0>f)return-28;
for(;d.streams[f];)f++;return d.xb(e,f).La;case 1:case 2:return 0;case 3:return e.flags;case 4:return f=v.get(),e.flags|=f,0;case 5:return f=v.Ea(),U[f+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return m[pa()>>2]=28,-1;default:return-28}}catch(g){if("undefined"==typeof d||"ErrnoError"!==g.name)throw g;return-g.$}},E:function(a,b){try{if(0===b)return-28;var c=d.Wa(),e=X(c)+1;if(b<e)return-68;S(c,G,a,b);return e}catch(f){if("undefined"==typeof d||"ErrnoError"!==f.name)throw f;
return-f.$}},A:function(a,b,c){try{var e=v.ka(a);e.sa||(e.sa=d.Ha(e.path));a=0;for(var f=d.ca(e,0,1),g=Math.floor(f/280);g<e.sa.length&&a+280<=c;){var k=e.sa[g];if("."===k){var n=e.node.id;var q=4}else if(".."===k)n=d.W(e.path,{parent:!0}).node.id,q=4;else{var p=d.ga(e.node,k);n=p.id;q=d.Na(p.mode)?2:d.Z(p.mode)?4:d.ua(p.mode)?10:8}w=[n>>>0,(l=n,1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[b+a>>2]=w[0];m[b+a+4>>2]=w[1];w=[280*(g+1)>>>0,(l=280*
(g+1),1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[b+a+8>>2]=w[0];m[b+a+12>>2]=w[1];U[b+a+16>>1]=280;E[b+a+18>>0]=q;S(k,G,b+a+19,256);a+=280;g+=1}d.ca(e,280*g,0);return a}catch(u){if("undefined"==typeof d||"ErrnoError"!==u.name)throw u;return-u.$}},l:function(a,b,c){v.Ja=c;try{var e=v.ka(a);switch(b){case 21509:return e.V?0:-59;case 21505:if(!e.V)return-59;if(e.V.ma.rc){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0];var f=v.Ea();m[f>>2]=25856;m[f+4>>2]=5;m[f+8>>2]=191;m[f+12>>2]=35387;for(var g=0;32>g;g++)E[f+g+17>>0]=a[g]||0}return 0;case 21510:case 21511:case 21512:return e.V?0:-59;case 21506:case 21507:case 21508:if(!e.V)return-59;if(e.V.ma.sc)for(f=v.Ea(),a=[],g=0;32>g;g++)a.push(E[f+g+17>>0]);return 0;case 21519:if(!e.V)return-59;f=v.Ea();return m[f>>2]=0;case 21520:return e.V?-28:-59;case 21531:return f=v.Ea(),d.lb(e,b,f);case 21523:if(!e.V)return-59;e.V.ma.tc&&(g=[24,80],f=v.Ea(),U[f>>1]=g[0],U[f+
2>>1]=g[1]);return 0;case 21524:return e.V?0:-59;case 21515:return e.V?0:-59;default:return-28}}catch(k){if("undefined"==typeof d||"ErrnoError"!==k.name)throw k;return-k.$}},k:function(a,b,c,e){v.Ja=e;try{b=v.Ya(b);b=v.ub(a,b);var f=e?v.get():0;return d.open(b,c,f).La}catch(g){if("undefined"==typeof d||"ErrnoError"!==g.name)throw g;return-g.$}},z:function(a,b){try{return a=v.Ya(a),v.lc(d.stat,a,b)}catch(c){if("undefined"==typeof d||"ErrnoError"!==c.name)throw c;return-c.$}},y:function(a,b,c){try{return b=
v.Ya(b),b=v.ub(a,b),0===c?d.qa(b):512===c?d.Ia(b):I("Invalid flags passed to unlinkat"),0}catch(e){if("undefined"==typeof d||"ErrnoError"!==e.name)throw e;return-e.$}},F:()=>!0,u:()=>{throw Infinity;},s:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));m[c>>2]=a.getSeconds();m[c+4>>2]=a.getMinutes();m[c+8>>2]=a.getHours();m[c+12>>2]=a.getDate();m[c+16>>2]=a.getMonth();m[c+20>>2]=a.getFullYear()-1900;m[c+24>>2]=a.getDay();b=(Y(a.getFullYear())?ab:bb)[a.getMonth()]+
a.getDate()-1;m[c+28>>2]=b|0;m[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var e=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();m[c+32>>2]=(b!=e&&a.getTimezoneOffset()==Math.min(e,b))|0},w:(a,b,c)=>{function e(q){return(q=q.toTimeString().match(/\(([A-Za-z ]+)\)$/))?q[1]:"GMT"}var f=(new Date).getFullYear(),g=new Date(f,0,1),k=new Date(f,6,1);f=g.getTimezoneOffset();var n=k.getTimezoneOffset();A[a>>2]=60*Math.max(f,n);m[b>>2]=Number(f!=n);a=e(g);
b=e(k);a=Ma(a);b=Ma(b);n<f?(A[c>>2]=a,A[c+4>>2]=b):(A[c>>2]=b,A[c+4>>2]=a)},j:()=>Date.now(),n:()=>performance.now(),v:()=>{I("OOM")},C:(a,b)=>{var c=0;Z().forEach((e,f)=>{var g=b+c;f=A[a+4*f>>2]=g;for(g=0;g<e.length;++g)E[f++>>0]=e.charCodeAt(g);E[f>>0]=0;c+=e.length+1});return 0},D:(a,b)=>{var c=Z();A[a>>2]=c.length;var e=0;c.forEach(f=>e+=f.length+1);A[b>>2]=e;return 0},x:R,f:function(a){try{var b=v.ka(a);d.close(b);return 0}catch(c){if("undefined"==typeof d||"ErrnoError"!==c.name)throw c;return c.$}},
B:function(a,b){try{var c=v.ka(a);E[b>>0]=c.V?2:d.Z(c.mode)?3:d.ua(c.mode)?7:4;U[b+2>>1]=0;w=[0,(l=0,1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[b+8>>2]=w[0];m[b+12>>2]=w[1];w=[0,(l=0,1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/4294967296)>>>0:0)];m[b+16>>2]=w[0];m[b+20>>2]=w[1];return 0}catch(e){if("undefined"==typeof d||"ErrnoError"!==e.name)throw e;return e.$}},r:function(a,b,c,e){try{a:{var f=v.ka(a);a=b;
b=void 0;for(var g=0,k=0;k<c;k++){var n=A[a>>2],q=A[a+4>>2];a+=8;var p=d.read(f,E,n,q,b);if(0>p){var u=-1;break a}g+=p;if(p<q)break;"undefined"!==typeof b&&(b+=p)}u=g}A[e>>2]=u;return 0}catch(z){if("undefined"==typeof d||"ErrnoError"!==z.name)throw z;return z.$}},t:function(a,b,c,e,f){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var g=v.ka(a);d.ca(g,b,e);w=[g.position>>>0,(l=g.position,1<=+Math.abs(l)?0<l?+Math.floor(l/4294967296)>>>0:~~+Math.ceil((l-+(~~l>>>0))/
4294967296)>>>0:0)];m[f>>2]=w[0];m[f+4>>2]=w[1];g.sa&&0===b&&0===e&&(g.sa=null);return 0}catch(k){if("undefined"==typeof d||"ErrnoError"!==k.name)throw k;return k.$}},q:function(a,b,c,e){try{a:{var f=v.ka(a);a=b;b=void 0;for(var g=0,k=0;k<c;k++){var n=A[a>>2],q=A[a+4>>2];a+=8;var p=d.write(f,E,n,q,b);if(0>p){var u=-1;break a}g+=p;"undefined"!==typeof b&&(b+=p)}u=g}A[e>>2]=u;return 0}catch(z){if("undefined"==typeof d||"ErrnoError"!==z.name)throw z;return z.$}},i:function(a){var b=N();try{return M.get(a)()}catch(c){O(b);
if(c!==c+0)throw c;P(1,0)}},a:function(a,b){var c=N();try{return M.get(a)(b)}catch(e){O(c);if(e!==e+0)throw e;P(1,0)}},b:function(a,b,c){var e=N();try{return M.get(a)(b,c)}catch(f){O(e);if(f!==f+0)throw f;P(1,0)}},h:function(a,b,c,e,f){var g=N();try{return M.get(a)(b,c,e,f)}catch(k){O(g);if(k!==k+0)throw k;P(1,0)}},d:function(a){var b=N();try{M.get(a)()}catch(c){O(b);if(c!==c+0)throw c;P(1,0)}},c:function(a,b){var c=N();try{M.get(a)(b)}catch(e){O(c);if(e!==e+0)throw e;P(1,0)}},e:function(a,b,c,e){var f=
N();try{M.get(a)(b,c,e)}catch(g){O(f);if(g!==g+0)throw g;P(1,0)}},g:(a,b,c,e)=>{function f(h,y,B){for(h="number"==typeof h?h.toString():h||"";h.length<y;)h=B[0]+h;return h}function g(h,y){return f(h,y,"0")}function k(h,y){function B(aa){return 0>aa?-1:0<aa?1:0}var D;0===(D=B(h.getFullYear()-y.getFullYear()))&&0===(D=B(h.getMonth()-y.getMonth()))&&(D=B(h.getDate()-y.getDate()));return D}function n(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),
0,3);case 3:return new Date(h.getFullYear(),0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function q(h){var y=h.Ca;for(h=new Date((new Date(h.Da+1900,0,1)).getTime());0<y;){var B=Y(h.getFullYear()),D=h.getMonth();B=(B?Na:Oa)[D];if(y>B-h.getDate())y-=B-h.getDate()+1,h.setDate(1),11>D?h.setMonth(D+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+y);break}}D=new Date(h.getFullYear()+
1,0,4);y=n(new Date(h.getFullYear(),0,4));D=n(D);return 0>=k(y,h)?0>=k(D,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var p=A[e+40>>2];e={Nc:m[e>>2],Mc:m[e+4>>2],cb:m[e+8>>2],tb:m[e+12>>2],eb:m[e+16>>2],Da:m[e+20>>2],ja:m[e+24>>2],Ca:m[e+28>>2],sd:m[e+32>>2],Lc:m[e+36>>2],Oc:p?p?L(G,p,void 0):"":""};c=c?L(G,c,void 0):"";p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C",
"%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var u in p)c=c.replace(new RegExp(u,"g"),p[u]);var z="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),C="January February March April May June July August September October November December".split(" ");p={"%a":h=>z[h.ja].substring(0,3),"%A":h=>z[h.ja],"%b":h=>C[h.eb].substring(0,
3),"%B":h=>C[h.eb],"%C":h=>g((h.Da+1900)/100|0,2),"%d":h=>g(h.tb,2),"%e":h=>f(h.tb,2," "),"%g":h=>q(h).toString().substring(2),"%G":h=>q(h),"%H":h=>g(h.cb,2),"%I":h=>{h=h.cb;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":h=>{for(var y=h.tb,B=Y(h.Da+1900)?Na:Oa,D=0,aa=0;aa<=h.eb-1;D+=B[aa++]);return g(y+D,3)},"%m":h=>g(h.eb+1,2),"%M":h=>g(h.Mc,2),"%n":()=>"\n","%p":h=>0<=h.cb&&12>h.cb?"AM":"PM","%S":h=>g(h.Nc,2),"%t":()=>"\t","%u":h=>h.ja||7,"%U":h=>g(Math.floor((h.Ca+7-h.ja)/7),2),"%V":h=>{var y=Math.floor((h.Ca+
7-(h.ja+6)%7)/7);2>=(h.ja+371-h.Ca-2)%7&&y++;if(y)53==y&&(B=(h.ja+371-h.Ca)%7,4==B||3==B&&Y(h.Da)||(y=1));else{y=52;var B=(h.ja+7-h.Ca-1)%7;(4==B||5==B&&Y(h.Da%400-1))&&y++}return g(y,2)},"%w":h=>h.ja,"%W":h=>g(Math.floor((h.Ca+7-(h.ja+6)%7)/7),2),"%y":h=>(h.Da+1900).toString().substring(2),"%Y":h=>h.Da+1900,"%z":h=>{h=h.Lc;var y=0<=h;h=Math.abs(h)/60;return(y?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":h=>h.Oc,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(u in p)c.includes(u)&&(c=c.replace(new RegExp(u,
"g"),p[u](e)));c=c.replace(/\0\0/g,"%");u=ka(c,!1);if(u.length>b)return 0;E.set(u,a);return u.length-1},o:a=>{if(!a)return 0;m[pa()>>2]=52;return-1}},F=function(){function a(c){F=c.exports;Ia=F.G;c=Ia.buffer;r.HEAP8=E=new Int8Array(c);r.HEAP16=U=new Int16Array(c);r.HEAPU8=G=new Uint8Array(c);r.HEAPU16=new Uint16Array(c);r.HEAP32=m=new Int32Array(c);r.HEAPU32=A=new Uint32Array(c);r.HEAPF32=new Float32Array(c);r.HEAPF64=new Float64Array(c);M=F.L;Fa.unshift(F.H);ba("wasm-instantiate");return F}var b=
{a:cb};Q++;if(r.instantiateWasm)try{return r.instantiateWasm(b,a)}catch(c){return J(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ra(da,W,b,function(c){a(c.instance)});return{}}(),La=a=>(La=F.I)(a),pa=()=>(pa=F.J)(),Aa=r._main=(a,b)=>(Aa=r._main=F.K)(a,b),P=(a,b)=>(P=F.M)(a,b),N=()=>(N=F.N)(),O=a=>(O=F.O)(a),la=a=>(la=F.P)(a),fa;V=function b(){fa||Da();fa||(V=b)};var Ua=!1;Da()});"object"===typeof exports&&"object"===typeof module?module.exports=ia:"function"===typeof define&&define.amd?
define([],function(){return ia}):"object"===typeof exports?exports.createGnuplot=ia:this.createGnuplot=ia})();
